# Generated by Django 5.2.1 on 2025-05-24 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='对话内容')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '对话',
                'verbose_name_plural': '对话',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='DialoguePractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_count', models.IntegerField(default=0, verbose_name='练习次数')),
                ('last_practice', models.DateTimeField(auto_now=True, verbose_name='最后练习时间')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.dialogue', verbose_name='对话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '练习记录',
                'verbose_name_plural': '练习记录',
                'ordering': ['-last_practice'],
                'unique_together': {('user', 'dialogue')},
            },
        ),
    ]
