# Generated by Django 5.2 on 2025-06-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userpoints"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserPoints",
        ),
    ]
