# Generated by Django 5.2.1 on 2025-05-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='官方回复'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='response_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回复时间'),
        ),
    ]
