# Generated by Django 5.2.1 on 2025-05-18 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('level', models.CharField(choices=[('info', '普通'), ('warning', '警告'), ('danger', '重要')], default='info', max_length=20, verbose_name='重要程度')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '网站公告',
                'verbose_name_plural': '网站公告',
                'ordering': ['-created_at'],
            },
        ),
    ]
