# Generated by Django 5.2.1 on 2025-06-10 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flashcard",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="flashcard",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
